import type { Metadata } from "next";
import GlobalProvider from "@/providers";
import "@/styles/styles.scss";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={"min-h-screen"}>
        <GlobalProvider>{children}</GlobalProvider>
      </body>
    </html>
  );
}
